const { neon } = require('@neondatabase/serverless');
const jwt = require('jsonwebtoken');

function setCors(req, res) {
  const o = req.headers.origin || '';
  const a = process.env.ALLOWED_ORIGIN || 'https://mayhaim.vercel.app';
  res.setHeader('Access-Control-Allow-Origin', (o===a||/^https:\/\/mayhaim[^.]*\.vercel\.app$/.test(o))?o:a);
  res.setHeader('Vary', 'Origin');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
}

function verifyToken(req) {
  const h = req.headers.authorization;
  if (!h || !h.startsWith('Bearer ')) return null;
  try {
    const decoded = jwt.verify(h.split(' ')[1], process.env.JWT_SECRET);
    if (decoded.partial || !decoded.mfa_verified) return null;
    return decoded;
  } catch { return null; }
}

const DEFAULT_SCENARIOS = [
  { id: 1, title: "B Execute via Hookah — Bind", rank: "SILVER", map: "Bind", type: "attack", difficulty: 2, description: "Exécution classique sur B site en passant par hookah. Le controller smoke CT et le duelist entre le premier.", guide: "1. Le controller smoke l'angle CT (sortie hookah) et le coin U-Hall\n2. L'initiator lance une flash par-dessus hookah pour aveugler les défenseurs\n3. Le duelist entre hookah en pre-aim CT dès la sortie\n4. Un second joueur suit et clear le coin gauche (derrière la caisse)\n5. Un troisième joueur entre par B main pour couper les rotations\n6. Plant derrière la grande boîte — difficile à défuser depuis CT", tips: "Ne jamais entrer hookah sans smoke CT — c'est un angle à mort garantie. En sortant, pre-aim immédiatement CT avant toute chose. La boîte centrale B est le meilleur spot de plant : elle donne couverture depuis toutes les entrées.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 2, title: "Défense A Short — Bind", rank: "SILVER", map: "Bind", type: "defense", difficulty: 2, description: "Tenir A site depuis les positions Short et CT. Objectif : forcer les attaquants à utiliser leurs utils avant d'entrer.", guide: "1. 1 joueur tient A short depuis le coin CT (angle sur l'entrée)\n2. 1 joueur hold elbow avec angle sur A main\n3. Sentinel place un trip au pied de short A pour détecter les pushes\n4. Controller garde une smoke pour urgence (smoke A main si rush)\n5. Si les attaquants entrent : ne pas peeker, attendre le crossfire short + elbow\n6. En retake : entrer par CT et showers TP simultanément", tips: "Ne jamais quitter le coin CT sans info — c'est la position la plus forte. Si tu entends des pas sur les toits de showers, informe ton équipe immédiatement. Le crossfire short + elbow rend l'entrée A très difficile sans smoke.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 3, title: "Retake B via Showers TP — Bind", rank: "GOLD", map: "Bind", type: "retake", difficulty: 3, description: "Reprendre B site en coordonnant une entrée par B main et une sortie du téléporteur showers.", guide: "1. 1-2 joueurs avancent par B main (côté long B)\n2. 1 joueur utilise le TP showers pour arriver côté garden B\n3. Flash le site depuis B main avant d'entrer\n4. Smoke U-Hall pour couper les renforts depuis hookah\n5. Pincer : un depuis B main, un depuis garden simultanément\n6. Ne defuser qu'une fois le site entièrement clear", tips: "Le TP showers est l'atout principal du retake B — arriver de deux côtés désorganise totalement les défenseurs. Écoute le spike pour localiser les ennemis. Ne jamais defuser seul si tu n'as pas confirmé les positions.", aim_mode: "w1w3ts_reload", aim_diff: "medium" },
  { id: 4, title: "Execute C coordonné — Haven", rank: "SILVER", map: "Haven", type: "attack", difficulty: 2, description: "Exécuter sur C site avec smoke CT et flash pour neutraliser le défenseur CT avant d'entrer.", guide: "1. Controller smoke CT C (l'angle dominant en sortant de C main)\n2. Controller smoke le coin C right si un défenseur y est habituel\n3. Initiator flash depuis C lobby au-dessus du mur\n4. Duelist entre le premier (pre-aim CT en sortant)\n5. Deuxième joueur clear le coin droit immédiatement\n6. Plant derrière la boîte centrale ou au fond selon le clear", tips: "CT est le seul angle vraiment dangereux sur C — une seule smoke suffit. Entre vite et plante rapidement, les rotations depuis A sont rapides sur Haven. Le coin C right est souvent oublié : check-le systématiquement.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 5, title: "Contrôle Mid Garage + Window — Haven", rank: "GOLD", map: "Haven", type: "defense", difficulty: 3, description: "Dominer le mid de Haven depuis garage et window pour bloquer les rotations et collecter l'info.", guide: "1. 1 joueur hold mid depuis le coin garage (vue sur window)\n2. 1 joueur hold window depuis mid (crossfire avec garage)\n3. Sentinel place un trip sur la porte B mid pour l'info\n4. Controller garde 1 smoke pour urgence mid\n5. Si push mid : smoke B door + crossfire garage + window simultanément\n6. Ne jamais rotater sans call — les rotations inutiles perdent des rounds", tips: "Celui qui contrôle mid sur Haven contrôle les rotations. Le crossfire garage + window est très difficile à traverser sans utils. Garde toujours une smoke pour l'urgence — ne la gaspille pas en début de round.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 6, title: "Retake A via Long + Short — Haven", rank: "GOLD", map: "Haven", type: "retake", difficulty: 3, description: "Reprendre A site en entrant par long A et short A simultanément pour pincer les défenseurs.", guide: "1. 1 joueur avance par long A (depuis CT)\n2. 1 joueur descend short A (depuis CT short)\n3. Initiator flash le site depuis l'entrée long A\n4. Smoke le coin CT box si un défenseur y est probable\n5. Pincer : un depuis long, un depuis short en même temps\n6. Defuser en couvrant long A et short simultanément", tips: "Long A est l'angle de post-plant le plus utilisé sur A Haven — priorité absolue. Si tu entres seul, utilise une flash + jiggle peek pour forcer un tir avant d'entrer. La coordination timing entre les deux joueurs est la clé.", aim_mode: "w1w3ts_reload", aim_diff: "medium" },
  { id: 7, title: "Execute B Heaven + Main — Split", rank: "SILVER", map: "Split", type: "attack", difficulty: 2, description: "Prendre B site en combinant une entrée par B heaven (depuis mid) et B main simultanément.", guide: "1. Controller smoke B heaven pour monter depuis mid en sécurité\n2. Controller smoke B window pour bloquer la vue depuis mid\n3. Initiator flash B main pour l'entry\n4. Joueur 1 monte heaven depuis mid (couvre tout le site depuis le haut)\n5. Joueurs 2-3 entrent B main simultanément\n6. Plant derrière le container central — difficile à défuser depuis heaven", tips: "Heaven donne une vue sur tout B site — le joueur là-haut doit caller chaque position. La smoke heaven pour monter est non-négociable. Back-B est l'angle le plus souvent oublié par les attaquants : check-le immédiatement.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 8, title: "Hold A CT Ropes + Main — Split", rank: "GOLD", map: "Split", type: "defense", difficulty: 3, description: "Défendre A site depuis CT avec un crossfire naturel entre la position ropes et A main.", guide: "1. 1 joueur tient ropes depuis CT (angle élevé sur l'entrée)\n2. 1 joueur hold A main depuis le coin CT\n3. Sentinel setup un trip sur A heaven pour détecter les flanks\n4. Controller garde une smoke pour ropes si besoin\n5. Ne jamais peeker sans info — attendre le push et crossfire\n6. Si perdus : reculer mid et attendre le retake", tips: "Le crossfire ropes + main rend l'entrée A quasiment impossible sans utils. La position ropes est dominante mais exposée aux flashs — recule si flash détectée. Heaven est le flank le plus dangereux : le sentinel doit obligatoirement le couvrir.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 9, title: "Retake B depuis CT + Mid Window — Split", rank: "GOLD", map: "Split", type: "retake", difficulty: 3, description: "Reprendre B site en entrant par CT et par mid window simultanément pour pincer les défenseurs.", guide: "1. 1 joueur entre B depuis CT direct\n2. 1 joueur passe par mid et descend window\n3. Flash le site depuis CT avant d'entrer\n4. Smoke le coin back-B si un défenseur y est probable\n5. Pincer : un depuis CT, un depuis window simultanément\n6. Defuser derrière le container — couverture depuis les deux angles", tips: "Back-B est le spot de post-plant préféré sur B Split — toujours le checker ou le smoker. Window donne un angle surprenant sur tout le site. Ne defuser jamais si back-B n'est pas confirmé clear.", aim_mode: "w1w3ts_reload", aim_diff: "medium" },
  { id: 10, title: "Execute A avec cassage de porte — Lotus", rank: "GOLD", map: "Lotus", type: "attack", difficulty: 3, description: "Exécuter sur A site en cassant la porte pour créer un angle supplémentaire et smoker tree + root.", guide: "1. Un joueur casse la porte A (le bruit peut masquer l'exécution)\n2. Controller smoke tree ET root simultanément\n3. Initiator flash depuis A main en direction du site\n4. Duelist entre le premier — pre-aim tree immédiatement\n5. Deuxième joueur clear root corner\n6. Plant derrière le stone ou spot default selon le clear", tips: "Tree est l'angle le plus mortel de A Lotus — il doit TOUJOURS être smoké en premier. Root est souvent tenu agressivement : approche avec une flash. Casser la porte crée du bruit — utilise ça stratégiquement pour masquer ton timing d'entrée.", aim_mode: "vox_ts2", aim_diff: "medium" },
  { id: 11, title: "Hold C depuis Mound — Lotus", rank: "GOLD", map: "Lotus", type: "defense", difficulty: 3, description: "Défendre C site depuis la position mound avec un angle dominant sur toute l'entrée principale.", guide: "1. 1 joueur prend mound (position haute, vue sur toute l'entrée C)\n2. 1 joueur hold le coin C link depuis le site\n3. Sentinel place un trip à l'entrée C main pour l'info\n4. Controller garde une smoke pour l'urgence (smoke C main si rush)\n5. Si push : le joueur mound engage le premier — le second flanke depuis link\n6. Ne jamais rester sur mound après avoir tiré — repositionne-toi", tips: "Mound est la position dominante de C Lotus mais très exposée aux grenades. Repositionne-toi après chaque engagement. Le trip sentinel à l'entrée est l'info la plus précieuse — ne jamais s'en priver.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 12, title: "Retake B via A Link + B Main — Lotus", rank: "GOLD", map: "Lotus", type: "retake", difficulty: 3, description: "Reprendre B site en coordonnant une entrée par B main et une par A link pour pincer.", guide: "1. 1 joueur entre B depuis B main (chemin direct)\n2. 1 joueur passe par A link pour arriver côté link B\n3. Flash le site depuis B main avant d'entrer\n4. Smoke le coin C connection pour bloquer les renforts\n5. Pincer : un depuis B main, un depuis link en même temps\n6. Defuser derrière le rocher central", tips: "Le rocher central B est le meilleur spot de défense post-plant sur Lotus. A link donne un angle de retake complètement inattendu — profite-en. Ne defuser jamais sans avoir confirmé les deux angles principaux.", aim_mode: "w1w3ts_reload", aim_diff: "medium" },
  { id: 13, title: "Execute B via Tunnel — Breeze", rank: "SILVER", map: "Breeze", type: "attack", difficulty: 2, description: "Exécuter sur B site en passant par le tunnel avec smoke CT et flash pour sécuriser l'entrée.", guide: "1. Controller smoke CT B (l'angle dominant en sortant du tunnel)\n2. Initiator flash dans le tunnel avant d'entrer\n3. Duelist entre le premier — pre-aim CT dès la sortie\n4. Deuxième joueur clear le coin Arco (à droite en sortant)\n5. Troisième joueur entre et couvre l'angle mid B\n6. Plant au centre du site ou derrière la caisse selon le clear", tips: "CT est l'angle le plus dangereux en sortie de tunnel — une smoke suffit mais elle est obligatoire. Arco est souvent oublié mais fréquemment tenu : check-le systématiquement. Ne t'entasse pas dans le tunnel — entre un par un rapidement.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 14, title: "Hold A avec mur Viper — Breeze", rank: "PLATINUM", map: "Breeze", type: "defense", difficulty: 4, description: "Tenir A site avec le mur de Viper pour créer un one-way et forcer les attaquants à se découvrir.", guide: "1. Viper place son mur en diagonale sur A main (créé un one-way)\n2. 1 joueur se positionne derrière le mur (one-way advantage)\n3. 1 joueur tient le pilier avec angle sur A site\n4. Viper place son orbe près de CT pour le post-plant\n5. Si execute : ulti Viper sur le spike pour deny le défuse\n6. Communiquer les traversées via le mur (= alert automatique)", tips: "Le mur Viper sur A Breeze est un des setups défensifs les plus forts du jeu — apprends le placement exact. Le one-way donne un avantage informationnel majeur. Si les attaquants ont Brimstone ou Astra pour re-smoker, prépare un plan B.", aim_mode: "pasu_reload", aim_diff: "hard" },
  { id: 15, title: "Retake A via Cave + Main — Breeze", rank: "GOLD", map: "Breeze", type: "retake", difficulty: 3, description: "Reprendre A site en combinant une entrée par A cave et une par A main pour pincer les défenseurs.", guide: "1. 1 joueur entre par A main (depuis CT)\n2. 1 joueur entre par cave (angle latéral inattendu)\n3. Flash le site depuis A main avant d'entrer\n4. Smoke le pilier si un défenseur s'y cache probable\n5. Pincer : un depuis main, un depuis cave simultanément\n6. Defuser derrière le pilier — seul point de couverture sur A", tips: "Cave est l'angle de retake le plus rapide et le plus inattendu sur A Breeze. Le pilier est la seule couverture sur le site — priorité absolue pour le défuse. Ne jamais defuser sans avoir confirmé pilier ET cave.", aim_mode: "w1w3ts_reload", aim_diff: "medium" },
  { id: 16, title: "Execute B depuis Attacker Side — Fracture", rank: "SILVER", map: "Fracture", type: "attack", difficulty: 2, description: "Exécuter sur B site via arcade avec smoke dish et flash pour sécuriser l'entrée principale.", guide: "1. Controller smoke dish (le défenseur dish est très agressif)\n2. Controller smoke CT B pour bloquer les rotations\n3. Initiator flash depuis le couloir arcade\n4. Duelist entre arcade — pre-aim dish corner puis CT\n5. Deuxième joueur clear le coin escaliers en entrant\n6. Plant derrière la grande boîte ou spot default B", tips: "Dish est la position la plus agressive de B Fracture — il faut le smoker ou le flasher sans exception. Les rotations depuis CT arrivent vite : plante rapidement dès que le site est clear. Le coin escaliers est souvent oublié mais régulièrement tenu.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 17, title: "Hold A Dish + Main Crossfire — Fracture", rank: "GOLD", map: "Fracture", type: "defense", difficulty: 3, description: "Défendre A site avec un crossfire entre dish et A main pour couvrir les deux entrées simultanément.", guide: "1. 1 joueur tient dish (vue sur A arcade et entrée)\n2. 1 joueur hold A main depuis le coin CT\n3. Sentinel place un trip sur l'entrée arcade pour l'info\n4. Controller garde une smoke pour urgence (smoke dish si flash)\n5. Si push arcade : dish engage, A main flanke par derrière\n6. Si push A main : A main engage, dish repositionne depuis CT", tips: "Dish est la meilleure position offensive de A Fracture mais très exposée aux flashs. Toujours avoir un joueur en soutien pour le trade. La trip sentinel sur arcade est l'info la plus précieuse — ne jamais s'en priver.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 18, title: "Retake B via Arcade + Rope — Fracture", rank: "GOLD", map: "Fracture", type: "retake", difficulty: 3, description: "Reprendre B site en entrant par arcade et par la corde simultanément pour pincer les défenseurs.", guide: "1. 1 joueur entre B depuis arcade (chemin direct)\n2. 1 joueur passe par la corde pour arriver côté rope B\n3. Flash le site depuis arcade avant d'entrer\n4. Smoke le coin CT B si un défenseur probable\n5. Pincer : un depuis arcade, un depuis rope en même temps\n6. Defuser derrière la grande boîte — couverture sur les deux angles", tips: "L'entrée depuis la corde est complètement inattendue sur le retake — maximise cet effet de surprise. CT B est le spot de post-plant le plus utilisé sur Fracture : flash ou smoke avant d'approcher. Ne defuse jamais si rope side n'est pas confirmé.", aim_mode: "w1w3ts_reload", aim_diff: "medium" },
  { id: 19, title: "Execute B Main — Pearl", rank: "SILVER", map: "Pearl", type: "attack", difficulty: 2, description: "Exécuter sur B site via B main avec smoke CT et flash pour sécuriser l'entrée unique.", guide: "1. Controller smoke CT B (l'angle dominant sur toute l'entrée)\n2. Initiator flash B main par-dessus le mur\n3. Duelist entre le premier — pre-aim le coin droit immédiatement\n4. Deuxième joueur check derrière la grande colonne\n5. Troisième joueur entre et couvre B screens\n6. Plant derrière la colonne ou dans le coin — difficile à défuser depuis CT", tips: "CT B est le seul angle vraiment dangereux en entrée — une smoke suffit mais elle est obligatoire. Le coin droit en entrant est fréquemment tenu agressivement. La colonne centrale offre la meilleure couverture pour le plant.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 20, title: "Hold A CT + Link Sentinel Setup — Pearl", rank: "GOLD", map: "Pearl", type: "defense", difficulty: 3, description: "Défendre A site avec un sentinel setup sur link et un crossfire CT + art pour couvrir les angles.", guide: "1. Sentinel (KJ/Cypher) setup un trip sur A link pour l'info\n2. 1 joueur tient CT A (angle dominant sur l'entrée via link)\n3. 1 joueur hold art depuis le site (crossfire avec CT)\n4. Controller garde une smoke pour urgence (smoke link si rush)\n5. Si push link : CT engage, art flanke depuis le site\n6. Ne jamais quitter CT sans call — c'est la position la plus forte", tips: "CT est la position la plus forte de A Pearl — ne jamais la quitter sans raison. Art est le second angle préféré des attaquants en post-plant : couvre-le systématiquement. Le trip sur link donne l'info gratuite dès le début du round.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 21, title: "Retake A via CT + Link — Pearl", rank: "GOLD", map: "Pearl", type: "retake", difficulty: 3, description: "Reprendre A site en entrant par CT et par link simultanément pour pincer les défenseurs.", guide: "1. 1 joueur entre A depuis CT direct\n2. 1 joueur passe par link pour arriver sur le flanc\n3. Flash le site depuis CT avant d'entrer\n4. Smoke art si un défenseur probable dans ce coin\n5. Pincer : un depuis CT, un depuis link simultanément\n6. Defuser derrière la structure centrale — couverture sur CT et art", tips: "CT est l'angle de post-plant le plus populaire sur A Pearl — flash avant d'y approcher. Art est le second spot préféré : smoke ou flash si tu n'as pas l'info. La structure centrale offre la meilleure protection pour le défuse.", aim_mode: "w1w3ts_reload", aim_diff: "medium" },
  { id: 22, title: "Défense B Site Hookah Control — Bind", rank: "GOLD", map: "Bind", type: "defense", difficulty: 3, description: "Tenir B site en contrôlant hookah et les angles depuis CT pour empêcher toute exécution.", guide: "1. Sentinel place un trip à l'entrée de hookah pour l'info précoce\n2. 1 joueur tient l'angle CT B avec vue sur hookah sortie\n3. 1 joueur hold le coin U-Hall pour couvrir le flanc\n4. Controller garde une smoke pour B main si rush détecté\n5. Si push hookah : le joueur CT engage immédiatement, U-Hall flanke\n6. Ne jamais avancer dans hookah seul — c'est un piège mortel", tips: "Le trip hookah est l'info la plus précieuse en défense B Bind — ne jamais l'oublier. CT est la position dominante : tu contrôles toute la sortie hookah depuis là. Si tu entends du bruit B main, appelle la rotation mais ne quitte pas CT.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 23, title: "Hold A depuis Heaven + Short — Haven", rank: "SILVER", map: "Haven", type: "defense", difficulty: 2, description: "Défendre A site avec un setup défensif depuis heaven et short pour couvrir toutes les entrées.", guide: "1. 1 joueur prend heaven A (vue dominante sur tout le site)\n2. 1 joueur hold short A depuis le coin mur\n3. Sentinel place un trip sur A long pour détecter les pushes\n4. Controller garde une smoke pour A main si rush\n5. Si push A main : heaven engage en premier, short flanke\n6. Si push A long : short engage, heaven couvre depuis le haut", tips: "Heaven donne un avantage de hauteur décisif sur A Haven — priorise cette position. Short A est le second angle clé : un joueur doit toujours le tenir. Le trip sur A long donne l'info gratuite dès les premières secondes du round.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 24, title: "Retake A via CT + Heaven — Split", rank: "PLATINUM", map: "Split", type: "retake", difficulty: 4, description: "Reprendre A site en coordonnant une entrée par CT et une montée par heaven pour pincer les post-plant.", guide: "1. 1 joueur entre A depuis CT direct (chemin principal)\n2. 1 joueur monte heaven depuis mid pour angle élevé\n3. Initiator flash le site depuis CT avant l'entrée\n4. Smoke le coin ramp si un défenseur probable\n5. Le joueur heaven clear les coins hauts pendant que CT entre\n6. Defuser depuis la position couverte par ramp — heaven surveille", tips: "Heaven donne un angle de retake dévastateur — impossible à ignorer pour les post-plant. CT est le chemin direct mais prévisible : flash obligatoire avant d'entrer. La coordination entre CT et heaven doit être simultanée pour maximiser la pince.", aim_mode: "vox_ts2", aim_diff: "hard" },
  { id: 25, title: "Retake A via Tree + Door — Lotus", rank: "PLATINUM", map: "Lotus", type: "retake", difficulty: 4, description: "Reprendre A site en utilisant la porte cassée et l'angle tree pour pincer les attaquants post-plant.", guide: "1. 1 joueur entre A depuis le côté tree (CT)\n2. 1 joueur passe par la porte cassée pour un angle latéral\n3. Initiator flash le site depuis tree side avant d'entrer\n4. Smoke root corner si un défenseur y est probable\n5. Pincer : un depuis tree side, un depuis la porte simultanément\n6. Defuser derrière le stone — meilleure couverture sur le site", tips: "La porte cassée offre un angle de retake inattendu que beaucoup d'attaquants oublient de couvrir. Tree side reste l'angle dominant — flash avant d'approcher. Ne defuse jamais sans avoir confirmé root ET tree clear.", aim_mode: "w1w3ts_reload", aim_diff: "hard" },
  { id: 26, title: "Execute A via Mid Door — Breeze", rank: "GOLD", map: "Breeze", type: "attack", difficulty: 3, description: "Exécuter sur A site en passant par mid door avec smoke pyramide et flash pour sécuriser l'entrée.", guide: "1. Controller smoke pyramide (l'angle dominant depuis A site)\n2. Controller smoke le coin CT A pour bloquer les rotations\n3. Initiator flash mid door avant l'entrée\n4. Duelist entre le premier — pre-aim pyramide immédiatement\n5. Deuxième joueur clear le coin cave à droite\n6. Plant derrière le pilier central — couverture maximale", tips: "Pyramide est l'angle le plus mortel de A Breeze depuis mid door — smoke obligatoire. Cave est souvent tenu agressivement : approche avec une flash prête. Le pilier central est le seul cover fiable pour le plant.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 27, title: "Execute A via A Main — Ascent", rank: "SILVER", map: "Ascent", type: "attack", difficulty: 2, description: "Exécuter sur A site en passant par A main avec smoke heaven et flash pour sécuriser l'entrée.", guide: "1. Controller smoke heaven A (l'angle dominant sur le site)\n2. Controller smoke le coin CT pour bloquer la vue défenseur\n3. Initiator flash A main par-dessus le mur\n4. Duelist entre le premier — pre-aim generator immédiatement\n5. Deuxième joueur clear le coin hell (sous heaven)\n6. Plant derrière generator — meilleure couverture depuis A main", tips: "Heaven est l'angle le plus dangereux sur A Ascent — une smoke suffit mais elle est obligatoire. Generator est le meilleur spot de plant : il offre une couverture depuis hell et main. Hell est souvent oublié par les attaquants : check-le systématiquement.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 28, title: "Execute B via B Main — Ascent", rank: "SILVER", map: "Ascent", type: "attack", difficulty: 2, description: "Exécuter sur B site en passant par B main avec smoke CT et flash pour ouvrir le site.", guide: "1. Controller smoke CT B (l'angle dominant en sortant de B main)\n2. Controller smoke le coin market pour bloquer les renforts\n3. Initiator flash B main avant d'entrer le site\n4. Duelist entre le premier — pre-aim lane immédiatement\n5. Deuxième joueur clear le coin back-site (derrière la boîte)\n6. Plant derrière la boîte centrale — difficile à défuser depuis CT", tips: "CT est l'angle le plus dangereux en entrée B Ascent — une smoke est non-négociable. Market est la route de rotation principale : smoke-le pour isoler le site. Lane est souvent tenu agressivement — pre-aim en sortant de B main.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 29, title: "Contrôle Mid Catwalk + Market — Ascent", rank: "GOLD", map: "Ascent", type: "defense", difficulty: 3, description: "Dominer le mid d'Ascent depuis catwalk et market pour bloquer les splits et collecter l'info.", guide: "1. 1 joueur hold catwalk depuis le coin (vue sur top mid)\n2. 1 joueur tient market door (crossfire avec catwalk)\n3. Sentinel place un trip sur bottom mid pour l'info\n4. Controller garde une smoke pour urgence mid\n5. Si push mid : crossfire catwalk + market simultanément\n6. Ne jamais avancer top mid sans info — c'est un death trap", tips: "Celui qui contrôle mid sur Ascent contrôle les splits A et B. Le crossfire catwalk + market est extrêmement dur à traverser sans utils. Le trip bottom mid donne l'alerte précoce — ne jamais s'en priver.", aim_mode: "w1w3ts_reload", aim_diff: "medium" },
  { id: 30, title: "Retake A via CT + Hell — Ascent", rank: "GOLD", map: "Ascent", type: "retake", difficulty: 3, description: "Reprendre A site en entrant par CT et par hell simultanément pour pincer les post-plant.", guide: "1. 1 joueur entre A depuis CT direct\n2. 1 joueur passe par hell pour un angle bas inattendu\n3. Flash le site depuis CT avant d'entrer\n4. Smoke generator si un défenseur probable\n5. Pincer : un depuis CT, un depuis hell en même temps\n6. Defuser derrière generator — couverture sur CT et main", tips: "Hell donne un angle de retake bas et inattendu que beaucoup d'attaquants oublient. Generator est le spot de post-plant le plus populaire sur A Ascent — flash ou smoke. La coordination entre CT et hell doit être parfaite pour réussir la pince.", aim_mode: "vox_ts2", aim_diff: "medium" },
  { id: 31, title: "Execute A via A Belt — Icebox", rank: "GOLD", map: "Icebox", type: "attack", difficulty: 3, description: "Exécuter sur A site en passant par belt avec smoke rafters et flash pour ouvrir le site.", guide: "1. Controller smoke rafters (le défenseur là-haut voit tout le site)\n2. Controller smoke le coin CT A pour bloquer les rotations\n3. Initiator flash A main depuis le couloir belt\n4. Duelist entre par belt — pre-aim nest immédiatement\n5. Deuxième joueur clear le coin pipes (à gauche en entrant)\n6. Plant sur le spot default — visible depuis belt pour le post-plant", tips: "Rafters est la position la plus forte de A Icebox — impossible d'entrer sans la smoker. Nest est souvent tenu agressivement par un sentinel : flash avant d'approcher. Le plant default permet de surveiller depuis belt en post-plant.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 32, title: "Execute B via B Orange — Icebox", rank: "SILVER", map: "Icebox", type: "attack", difficulty: 2, description: "Exécuter sur B site en passant par orange avec smoke CT et flash pour sécuriser l'entrée.", guide: "1. Controller smoke CT B (l'angle dominant depuis le fond du site)\n2. Initiator flash orange avant d'entrer\n3. Duelist entre le premier — pre-aim yellow immédiatement\n4. Deuxième joueur clear le coin green (côté gauche)\n5. Troisième joueur couvre kitchen depuis orange\n6. Plant derrière la grande caisse — couverture depuis orange", tips: "CT B est l'angle le plus dangereux en entrée — une smoke suffit mais elle est obligatoire. Yellow est souvent tenu agressivement : pre-aim en entrant. Green est fréquemment oublié mais régulièrement occupé par un sentinel.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 33, title: "Hold B Kitchen + Yellow Setup — Icebox", rank: "GOLD", map: "Icebox", type: "defense", difficulty: 3, description: "Défendre B site avec un crossfire entre kitchen et yellow pour couvrir toutes les entrées.", guide: "1. 1 joueur tient yellow (vue sur orange et entrée B)\n2. 1 joueur hold kitchen (crossfire avec yellow)\n3. Sentinel place un trip sur l'entrée orange pour l'info\n4. Controller garde une smoke pour orange si rush détecté\n5. Si push orange : yellow engage, kitchen flanke\n6. Si push green : kitchen engage, yellow repositionne", tips: "Le crossfire yellow + kitchen rend l'entrée B très difficile sans utils. Yellow est exposé aux flashs — recule si une flash est annoncée. Le trip orange est l'info la plus précieuse en défense B Icebox.", aim_mode: "w1w3ts_reload", aim_diff: "medium" },
  { id: 34, title: "Retake A via Rafters + Belt — Icebox", rank: "PLATINUM", map: "Icebox", type: "retake", difficulty: 4, description: "Reprendre A site en montant par rafters et en entrant par belt pour pincer les attaquants.", guide: "1. 1 joueur monte rafters depuis CT (angle élevé dominant)\n2. 1 joueur entre par belt (chemin direct)\n3. Flash le site depuis belt avant d'entrer\n4. Smoke nest si un défenseur y est probable\n5. Pincer : un depuis rafters (haut), un depuis belt (bas)\n6. Defuser derrière le container — couverture depuis rafters", tips: "Rafters donne un angle de retake dévastateur impossible à ignorer pour les post-plant. Belt est direct mais prévisible — flash obligatoire. La différence de hauteur entre rafters et belt rend la pince extrêmement difficile à contrer.", aim_mode: "vox_ts2", aim_diff: "hard" },
  { id: 35, title: "Execute A via A Main — Sunset", rank: "SILVER", map: "Sunset", type: "attack", difficulty: 2, description: "Exécuter sur A site en passant par A main avec smoke elbow et flash pour ouvrir le site.", guide: "1. Controller smoke elbow (le défenseur là voit toute l'entrée)\n2. Controller smoke le coin heaven pour bloquer la vue haute\n3. Initiator flash A main avant d'entrer\n4. Duelist entre le premier — pre-aim site center immédiatement\n5. Deuxième joueur clear le coin back-site à droite\n6. Plant derrière la structure centrale — couverture depuis A main", tips: "Elbow est l'angle le plus mortel de A Sunset — smoke obligatoire avant d'entrer. Heaven donne un angle élevé dangereux : smoke-le si possible. La structure centrale est le meilleur spot de plant pour le post-plant depuis main.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 36, title: "Hold B depuis Market + CT — Sunset", rank: "GOLD", map: "Sunset", type: "defense", difficulty: 3, description: "Défendre B site avec un crossfire depuis market et CT pour couvrir les deux entrées principales.", guide: "1. 1 joueur tient market (vue sur B main et entrée)\n2. 1 joueur hold CT B (crossfire avec market)\n3. Sentinel place un trip sur B main pour l'info précoce\n4. Controller garde une smoke pour B main si rush détecté\n5. Si push B main : market engage le premier, CT flanke\n6. Ne jamais avancer dans B main seul — attendre le crossfire", tips: "Le crossfire market + CT est la clé de la défense B Sunset. Market est la position agressive — recule après chaque engagement. Le trip B main donne l'info gratuite : ne jamais s'en priver en début de round.", aim_mode: "pasu_reload", aim_diff: "medium" },
  { id: 37, title: "Retake Mid via Courtyard — Sunset", rank: "PLATINUM", map: "Sunset", type: "retake", difficulty: 4, description: "Reprendre le contrôle du mid en entrant par courtyard avec des utils pour flush les défenseurs.", guide: "1. Initiator lance un drone ou une haunt pour info mid\n2. Controller smoke les angles dominants (top mid)\n3. Flash courtyard avant d'entrer\n4. 1 joueur entre courtyard — clear les coins latéraux\n5. 1 joueur couvre depuis le côté opposé\n6. Une fois mid secure, décider du split A ou B", tips: "Le mid de Sunset est crucial pour les rotations — le reprendre change le round. Courtyard est l'entrée la plus sûre pour reprendre mid. Toujours utiliser un drone ou une haunt avant d'entrer — le mid est dangereux sans info.", aim_mode: "w1w3ts_reload", aim_diff: "hard" },
  { id: 38, title: "Execute B via B Main — Abyss", rank: "GOLD", map: "Abyss", type: "attack", difficulty: 3, description: "Exécuter sur B site en passant par B main avec smoke heaven et flash pour sécuriser l'entrée.", guide: "1. Controller smoke heaven B (le défenseur là-haut contrôle tout)\n2. Controller smoke le coin CT B pour bloquer les rotations\n3. Initiator flash B main avant d'entrer\n4. Duelist entre le premier — pre-aim pillar immédiatement\n5. Deuxième joueur clear le coin sous heaven\n6. Plant derrière pillar — couverture maximale depuis B main", tips: "Heaven est la position dominante de B Abyss — impossible d'entrer sans la smoker. Attention aux chutes : les bords du site sont mortels sur Abyss. Pillar est le meilleur cover de plant — ne plante jamais à découvert.", aim_mode: "vox_ts2", aim_diff: "medium" },
  { id: 39, title: "Hold A depuis Bridge + CT — Abyss", rank: "SILVER", map: "Abyss", type: "defense", difficulty: 2, description: "Défendre A site avec un crossfire entre bridge et CT pour contrôler les entrées.", guide: "1. 1 joueur tient bridge (vue sur A main et l'entrée)\n2. 1 joueur hold CT A (crossfire avec bridge)\n3. Sentinel place un trip sur A main pour l'info\n4. Controller garde une smoke pour A main si rush\n5. Si push A main : bridge engage, CT flanke\n6. Attention aux bords — ne jamais reculer trop près du vide", tips: "Bridge est la position la plus forte de A Abyss mais attention aux chutes accidentelles. Le crossfire bridge + CT rend l'entrée A très difficile. Sur Abyss, la conscience spatiale est cruciale — les bords sont mortels.", aim_mode: "pokeball_frenzy", aim_diff: "medium" },
  { id: 40, title: "Retake B via CT + Heaven — Abyss", rank: "PLATINUM", map: "Abyss", type: "retake", difficulty: 4, description: "Reprendre B site en entrant par CT et en montant heaven pour pincer les post-plant.", guide: "1. 1 joueur entre B depuis CT direct\n2. 1 joueur monte heaven B pour l'angle élevé\n3. Flash le site depuis CT avant d'entrer\n4. Smoke pillar si un défenseur probable\n5. Pincer : un depuis CT, un depuis heaven simultanément\n6. Defuser derrière pillar — heaven surveille tout le site", tips: "Heaven donne un angle de retake décisif sur B Abyss — priorise cette montée. CT est prévisible mais nécessaire — flash obligatoire. Attention aux knockbacks près des bords du site pendant le retake.", aim_mode: "w1w3ts_reload", aim_diff: "hard" },
];

module.exports = async function handler(req, res) {
  setCors(req, res);
  if (req.method === 'OPTIONS') return res.status(200).end();

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const decoded = verifyToken(req);
  if (!decoded) return res.status(401).json({ error: 'Non autorisé' });
  if (decoded.role !== 'admin') return res.status(403).json({ error: 'Admin uniquement' });

  const { scenarios } = req.body || {};
  const list = Array.isArray(scenarios) && scenarios.length > 0 ? scenarios : DEFAULT_SCENARIOS;

  const sql = neon(process.env.DATABASE_URL);

  await sql`CREATE TABLE IF NOT EXISTS scenarios (
    id SERIAL PRIMARY KEY,
    title TEXT,
    rank TEXT,
    map TEXT,
    type TEXT,
    difficulty INT,
    description TEXT,
    guide TEXT,
    tips TEXT,
    aim_mode TEXT,
    aim_diff TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )`;

  await sql`DELETE FROM scenarios`;

  for (const s of list) {
    await sql`INSERT INTO scenarios (title, rank, map, type, difficulty, description, guide, tips, aim_mode, aim_diff)
      VALUES (${s.title}, ${s.rank}, ${s.map}, ${s.type}, ${s.difficulty}, ${s.description}, ${s.guide}, ${s.tips}, ${s.aim_mode}, ${s.aim_diff})`;
  }

  return res.status(200).json({ success: true, count: list.length, message: `${list.length} scénarios insérés avec succès` });
};
